// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EmptyBox: typeof import('./src/components/empty-box/index.vue')['default']
    EmptyIcon: typeof import('./src/components/icons/EmptyIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StreamPlayer: typeof import('./src/components/StreamPlayer.vue')['default']
  }
}
